// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file calculator/v1/calculator.proto (package calculator.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file calculator/v1/calculator.proto.
 */
export const file_calculator_v1_calculator: GenFile = /*@__PURE__*/
  fileDesc("Ch5jYWxjdWxhdG9yL3YxL2NhbGN1bGF0b3IucHJvdG8SDWNhbGN1bGF0b3IudjEiQwoSQ2FsY3VsYXRpb25SZXF1ZXN0EgwKBG51bTEYASABKAESDAoEbnVtMhgCIAEoARIRCglvcGVyYXRpb24YAyABKAkiJQoTQ2FsY3VsYXRpb25SZXNwb25zZRIOCgZyZXN1bHQYASABKAEyaQoRQ2FsY3VsYXRvclNlcnZpY2USVAoJQ2FsY3VsYXRlEiEuY2FsY3VsYXRvci52MS5DYWxjdWxhdGlvblJlcXVlc3QaIi5jYWxjdWxhdG9yLnYxLkNhbGN1bGF0aW9uUmVzcG9uc2UiAEJMWkpnaXRodWIuY29tL3h5MDgwMjAzMDMvY2FsY3VsYXRvci9iYWNrZW5kL2dlbi9nby9jYWxjdWxhdG9yL3YxO2NhbGN1bGF0b3J2MWIGcHJvdG8z");

/**
 * @generated from message calculator.v1.CalculationRequest
 */
export type CalculationRequest = Message<"calculator.v1.CalculationRequest"> & {
  /**
   * @generated from field: double num1 = 1;
   */
  num1: number;

  /**
   * @generated from field: double num2 = 2;
   */
  num2: number;

  /**
   * "+", "-", "*", "/"
   *
   * @generated from field: string operation = 3;
   */
  operation: string;
};

/**
 * Describes the message calculator.v1.CalculationRequest.
 * Use `create(CalculationRequestSchema)` to create a new message.
 */
export const CalculationRequestSchema: GenMessage<CalculationRequest> = /*@__PURE__*/
  messageDesc(file_calculator_v1_calculator, 0);

/**
 * @generated from message calculator.v1.CalculationResponse
 */
export type CalculationResponse = Message<"calculator.v1.CalculationResponse"> & {
  /**
   * @generated from field: double result = 1;
   */
  result: number;
};

/**
 * Describes the message calculator.v1.CalculationResponse.
 * Use `create(CalculationResponseSchema)` to create a new message.
 */
export const CalculationResponseSchema: GenMessage<CalculationResponse> = /*@__PURE__*/
  messageDesc(file_calculator_v1_calculator, 1);

/**
 * @generated from service calculator.v1.CalculatorService
 */
export const CalculatorService: GenService<{
  /**
   * @generated from rpc calculator.v1.CalculatorService.Calculate
   */
  calculate: {
    methodKind: "unary";
    input: typeof CalculationRequestSchema;
    output: typeof CalculationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_calculator_v1_calculator, 0);

